In [1]:
from pathlib import Path
from keyword_search_evaluation import get_scores

/home/adamp/school/cmpt419/layman-scientific-embeddings/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
MODELS_PATH = Path("models")

In [3]:
def print_model_scores(model_path: str | Path):
    scores = get_scores(model_path)
    print(model_path)
    print(f"Full match score: {scores["perfect_match_score"] * 100:.2f}%")
    print(f"Related keywords score: {scores["related_keyword_score"] * 100:.2f}%")

In [4]:
for model_path in MODELS_PATH.iterdir():
    print_model_scores(model_path)
    print("")

You are trying to use a model that was created with Sentence Transformers version 5.3.0, but you're currently using version 5.2.3. This might cause unexpected behavior or errors. In that case, try to update to the latest version.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 833.26it/s, Materializing param=pooler.dense.weight]
You are trying to use a model that was created with Sentence Transformers version 5.3.0, but you're currently using version 5.2.3. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

models/vanilla-finetuned
Full match score: 43.68%
Related keywords score: 5.86%

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 905.89it/s, Materializing param=pooler.dense.weight]
You are trying to use a model that was created with Sentence Transformers version 5.3.0, but you're currently using version 5.2.3. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

models/jargon-layman-finetuned-0.50
Full match score: 46.05%
Related keywords score: 6.05%

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 902.15it/s, Materializing param=pooler.dense.weight]
You are trying to use a model that was created with Sentence Transformers version 5.3.0, but you're currently using version 5.2.3. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

models/jargon-layman-finetuned-0.75
Full match score: 45.55%
Related keywords score: 6.06%

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 903.06it/s, Materializing param=pooler.dense.weight]
You are trying to use a model that was created with Sentence Transformers version 5.3.0, but you're currently using version 5.2.3. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

models/jargon-layman-finetuned-1.00
Full match score: 45.95%
Related keywords score: 6.12%

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 875.99it/s, Materializing param=pooler.dense.weight]

models/jargon-layman-finetuned-0.25
Full match score: 45.65%
Related keywords score: 5.99%

In [5]:
print_model_scores("allenai/scibert_scivocab_uncased")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
No sentence-transformers model found with name allenai/scibert_scivocab_uncased. Creating a new one with mean pooling.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1185.55it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: allenai/scibert_scivocab_uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

allenai/scibert_scivocab_uncased
Full match score: 11.46%
Related keywords score: 1.94%

# Results

| Model | Exact keyword match score | Related keyword score |
|---|---|---|
| allenai/scibert_scivocab_uncased | 11.46% | 1.94% |
| vanilla-finetuned | <u>43.68%</u> | <u>5.86%</u> |
| jargon-layman-finetuned | **45.95%** | **6.12%** |

In [6]:
import pandas as pd

In [7]:
scores_for_select_model = get_scores("models/jargon-layman-finetuned-1.00")
search_results: list[list[dict[str, float]]] = scores_for_select_model["search_results"]
search_df: pd.DataFrame = scores_for_select_model["search_df"]

You are trying to use a model that was created with Sentence Transformers version 5.3.0, but you're currently using version 5.2.3. This might cause unexpected behavior or errors. In that case, try to update to the latest version.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 975.47it/s, Materializing param=pooler.dense.weight]

In [8]:
search_results

[[{'corpus_id': 0, 'score': 0.9999999403953552},
  {'corpus_id': 861, 'score': 0.8305516242980957},
  {'corpus_id': 597, 'score': 0.7182247638702393},
  {'corpus_id': 11, 'score': 0.7039348483085632},
  {'corpus_id': 1, 'score': 0.7026268839836121},
  {'corpus_id': 595, 'score': 0.6995381712913513},
  {'corpus_id': 599, 'score': 0.6906185150146484},
  {'corpus_id': 855, 'score': 0.6670401096343994},
  {'corpus_id': 14, 'score': 0.6629663109779358},
  {'corpus_id': 858, 'score': 0.6508963108062744},
  {'corpus_id': 10, 'score': 0.6384038925170898},
  {'corpus_id': 600, 'score': 0.6352406144142151},
  {'corpus_id': 849, 'score': 0.6288851499557495},
  {'corpus_id': 732, 'score': 0.6273906230926514},
  {'corpus_id': 6, 'score': 0.6255139112472534}],
 [{'corpus_id': 0, 'score': 0.6528292894363403},
  {'corpus_id': 1, 'score': 0.635375440120697},
  {'corpus_id': 171, 'score': 0.6244080662727356},
  {'corpus_id': 173, 'score': 0.6028590202331543},
  {'corpus_id': 11, 'score': 0.5801800489425659},
  {'corpus_id': 10, 'score': 0.5759481191635132},
  {'corpus_id': 856, 'score': 0.5750640630722046},
  {'corpus_id': 13, 'score': 0.5727414488792419},
  {'corpus_id': 123, 'score': 0.5668813586235046},
  {'corpus_id': 7, 'score': 0.5632420778274536},
  {'corpus_id': 858, 'score': 0.5593488812446594},
  {'corpus_id': 861, 'score': 0.550908088684082},
  {'corpus_id': 411, 'score': 0.5502385497093201},
  {'corpus_id': 901, 'score': 0.546503484249115},
  {'corpus_id': 849, 'score': 0.5454614162445068}],
 [{'corpus_id': 2, 'score': 0.7996904850006104},
  {'corpus_id': 603, 'score': 0.6382358074188232},
  {'corpus_id': 51, 'score': 0.6260545253753662},
  {'corpus_id': 1, 'score': 0.6078271269798279},
  {'corpus_id': 5, 'score': 0.6044996976852417},
  {'corpus_id': 734, 'score': 0.5896965265274048},
  {'corpus_id': 0, 'score': 0.5816879868507385},
  {'corpus_id': 263, 'score': 0.574393630027771},
  {'corpus_id': 849, 'score': 0.5725365877151489},
  {'corpus_id': 11, 'score': 0.5689886808395386},
  {'corpus_id': 856, 'score': 0.567290186882019},
  {'corpus_id': 858, 'score': 0.5663633942604065},
  {'corpus_id': 9, 'score': 0.5617485046386719},
  {'corpus_id': 7, 'score': 0.5615428686141968},
  {'corpus_id': 597, 'score': 0.5555469393730164}],
 [{'corpus_id': 3, 'score': 0.6907442808151245},
  {'corpus_id': 10, 'score': 0.6818801760673523},
  {'corpus_id': 5, 'score': 0.6584975719451904},
  {'corpus_id': 858, 'score': 0.630008339881897},
  {'corpus_id': 861, 'score': 0.6205291748046875},
  {'corpus_id': 732, 'score': 0.6200488805770874},
  {'corpus_id': 0, 'score': 0.6171999573707581},
  {'corpus_id': 856, 'score': 0.6064527034759521},
  {'corpus_id': 600, 'score': 0.6059736609458923},
  {'corpus_id': 14, 'score': 0.6010624170303345},
  {'corpus_id': 848, 'score': 0.5879223346710205},
  {'corpus_id': 7, 'score': 0.5839179754257202},
  {'corpus_id': 743, 'score': 0.5779528021812439},
  {'corpus_id': 51, 'score': 0.5739346742630005},
  {'corpus_id': 855, 'score': 0.5736929178237915}],
 [{'corpus_id': 4, 'score': 0.6107138395309448},
  {'corpus_id': 683, 'score': 0.5885292291641235},
  {'corpus_id': 10, 'score': 0.5882493257522583},
  {'corpus_id': 0, 'score': 0.5788608193397522},
  {'corpus_id': 771, 'score': 0.5787728428840637},
  {'corpus_id': 878, 'score': 0.5763017535209656},
  {'corpus_id': 804, 'score': 0.5739396810531616},
  {'corpus_id': 401, 'score': 0.5739396810531616},
  {'corpus_id': 11, 'score': 0.572052001953125},
  {'corpus_id': 13, 'score': 0.5705766081809998},
  {'corpus_id': 3, 'score': 0.5613718628883362},
  {'corpus_id': 679, 'score': 0.5607158541679382},
  {'corpus_id': 877, 'score': 0.5482783317565918},
  {'corpus_id': 7, 'score': 0.5468131303787231},
  {'corpus_id': 1, 'score': 0.5397067070007324}],
 [{'corpus_id': 5, 'score': 0.7182781100273132},
  {'corpus_id': 856, 'score': 0.6819106936454773},
  {'corpus_id': 11, 'score': 0.676662266254425},
  {'corpus_id': 0, 'score': 0.6698215007781982},
  {'corpus_id': 14, 'score': 0.6573306322097778},
  {'corpus_id': 51, 'score': 0.6505109071731567},
  {'corpus_id': 603, 'score': 0.6421670317649841},
  {'corpus_id': 861, 'score': 0.6201757192611694},
  {'corpus_id': 600, 'score': 0.6164600253105164},
  {'corpus_id': 848, 'score': 0.6062893867492676},
  {'corpus_id': 12, 'score': 0.6058887243270874},
  {'corpus_id': 743, 'score': 0.602695882320404},
  {'corpus_id': 731, 'score': 0.59906005859375},
  {'corpus_id': 597, 'score': 0.5964024066925049},
  {'corpus_id': 3, 'score': 0.5959376096725464}],
 [{'corpus_id': 0, 'score': 0.7059997916221619},
  {'corpus_id': 11, 'score': 0.6979959011077881},
  {'corpus_id': 861, 'score': 0.6699896454811096},
  {'corpus_id': 597, 'score': 0.642662763595581},
  {'corpus_id': 9, 'score': 0.6336498260498047},
  {'corpus_id': 6, 'score': 0.6258001923561096},
  {'corpus_id': 8, 'score': 0.6178876161575317},
  {'corpus_id': 599, 'score': 0.6117876768112183},
  {'corpus_id': 855, 'score': 0.6107263565063477},
  {'corpus_id': 1, 'score': 0.6070254445075989},
  {'corpus_id': 14, 'score': 0.6069376468658447},
  {'corpus_id': 856, 'score': 0.5920400619506836},
  {'corpus_id': 595, 'score': 0.5855595469474792},
  {'corpus_id': 596, 'score': 0.5645492076873779},
  {'corpus_id': 848, 'score': 0.5496470332145691}],
 [{'corpus_id': 7, 'score': 0.7638722658157349},
  {'corpus_id': 3, 'score': 0.6685293316841125},
  {'corpus_id': 11, 'score': 0.6201738715171814},
  {'corpus_id': 13, 'score': 0.5931737422943115},
  {'corpus_id': 774, 'score': 0.5924891829490662},
  {'corpus_id': 10, 'score': 0.586728036403656},
  {'corpus_id': 121, 'score': 0.5863888263702393},
  {'corpus_id': 527, 'score': 0.5757374167442322},
  {'corpus_id': 6, 'score': 0.5735355615615845},
  {'corpus_id': 120, 'score': 0.5725286602973938},
  {'corpus_id': 600, 'score': 0.5705201625823975},
  {'corpus_id': 856, 'score': 0.5673012733459473},
  {'corpus_id': 2, 'score': 0.5670880079269409},
  {'corpus_id': 735, 'score': 0.565617561340332},
  {'corpus_id': 14, 'score': 0.5652996301651001}],
 [{'corpus_id': 8, 'score': 0.7662015557289124},
  {'corpus_id': 6, 'score': 0.6594634652137756},
  {'corpus_id': 9, 'score': 0.6335467100143433},
  {'corpus_id': 11, 'score': 0.5917148590087891},
  {'corpus_id': 0, 'score': 0.589771032333374},
  {'corpus_id': 1, 'score': 0.5893043279647827},
  {'corpus_id': 14, 'score': 0.5632539391517639},
  {'corpus_id': 188, 'score': 0.5575897693634033},
  {'corpus_id': 861, 'score': 0.5525088906288147},
  {'corpus_id': 856, 'score': 0.5482473373413086},
  {'corpus_id': 123, 'score': 0.544905960559845},
  {'corpus_id': 124, 'score': 0.5435790419578552},
  {'corpus_id': 2, 'score': 0.5413930416107178},
  {'corpus_id': 171, 'score': 0.5407733917236328},
  {'corpus_id': 165, 'score': 0.5359449982643127}],
 [{'corpus_id': 9, 'score': 0.7205550670623779},
  {'corpus_id': 0, 'score': 0.646556556224823},
  {'corpus_id': 2, 'score': 0.6462857723236084},
  {'corpus_id': 10, 'score': 0.6285594701766968},
  {'corpus_id': 849, 'score': 0.6273616552352905},
  {'corpus_id': 609, 'score': 0.61933434009552},
  {'corpus_id': 861, 'score': 0.6059778928756714},
  {'corpus_id': 901, 'score': 0.6055251359939575},
  {'corpus_id': 599, 'score': 0.601482093334198},
  {'corpus_id': 1, 'score': 0.6005315780639648},
  {'corpus_id': 7, 'score': 0.5990879535675049},
  {'corpus_id': 12, 'score': 0.5989893674850464},
  {'corpus_id': 123, 'score': 0.5976281762123108},
  {'corpus_id': 11, 'score': 0.59271240234375},
  {'corpus_id': 856, 'score': 0.5907048583030701}],
 [{'corpus_id': 10, 'score': 0.7711683511734009},
  {'corpus_id': 3, 'score': 0.672260046005249},
  {'corpus_id': 0, 'score': 0.6379205584526062},
  {'corpus_id': 7, 'score': 0.6263835430145264},
  {'corpus_id': 11, 'score': 0.5843480825424194},
  {'corpus_id': 5, 'score': 0.5843348503112793},
  {'corpus_id': 861, 'score': 0.5781022906303406},
  {'corpus_id': 14, 'score': 0.5773743391036987},
  {'corpus_id': 427, 'score': 0.5771194696426392},
  {'corpus_id': 8, 'score': 0.5682920813560486},
  {'corpus_id': 416, 'score': 0.5646927356719971},
  {'corpus_id': 9, 'score': 0.5438950061798096},
  {'corpus_id': 878, 'score': 0.5425330400466919},
  {'corpus_id': 528, 'score': 0.539486825466156},
  {'corpus_id': 6, 'score': 0.5307090878486633}],
 [{'corpus_id': 0, 'score': 0.7678189873695374},
  {'corpus_id': 855, 'score': 0.7584264278411865},
  {'corpus_id': 597, 'score': 0.7309689521789551},
  {'corpus_id': 595, 'score': 0.7282483577728271},
  {'corpus_id': 11, 'score': 0.7208269238471985},
  {'corpus_id': 861, 'score': 0.7136536836624146},
  {'corpus_id': 599, 'score': 0.7021211981773376},
  {'corpus_id': 858, 'score': 0.6811800003051758},
  {'corpus_id': 609, 'score': 0.6713383197784424},
  {'corpus_id': 14, 'score': 0.6663274765014648},
  {'corpus_id': 10, 'score': 0.6507327556610107},
  {'corpus_id': 850, 'score': 0.6376866102218628},
  {'corpus_id': 743, 'score': 0.6371219158172607},
  {'corpus_id': 9, 'score': 0.6301124095916748},
  {'corpus_id': 8, 'score': 0.6269880533218384}],
 [{'corpus_id': 0, 'score': 0.7402379512786865},
  {'corpus_id': 5, 'score': 0.7165442109107971},
  {'corpus_id': 855, 'score': 0.7058462500572205},
  {'corpus_id': 11, 'score': 0.7009133100509644},
  {'corpus_id': 743, 'score': 0.6950238943099976},
  {'corpus_id': 861, 'score': 0.6935797929763794},
  {'corpus_id': 599, 'score': 0.6893773674964905},
  {'corpus_id': 856, 'score': 0.6874040961265564},
  {'corpus_id': 595, 'score': 0.6853257417678833},
  {'corpus_id': 848, 'score': 0.6832426190376282},
  {'corpus_id': 597, 'score': 0.682087779045105},
  {'corpus_id': 858, 'score': 0.6784895658493042},
  {'corpus_id': 849, 'score': 0.6745448708534241},
  {'corpus_id': 603, 'score': 0.669808566570282},
  {'corpus_id': 731, 'score': 0.6640816330909729}],
 [{'corpus_id': 853, 'score': 0.6499210000038147},
  {'corpus_id': 189, 'score': 0.6474235653877258},
  {'corpus_id': 179, 'score': 0.6302973031997681},
  {'corpus_id': 184, 'score': 0.6260231733322144},
  {'corpus_id': 13, 'score': 0.6254796981811523},
  {'corpus_id': 127, 'score': 0.6253162622451782},
  {'corpus_id': 178, 'score': 0.620659351348877},
  {'corpus_id': 605, 'score': 0.6132285594940186},
  {'corpus_id': 607, 'score': 0.6067557334899902},
  {'corpus_id': 409, 'score': 0.6016460061073303},
  {'corpus_id': 126, 'score': 0.5997742414474487},
  {'corpus_id': 606, 'score': 0.5964897871017456},
  {'corpus_id': 599, 'score': 0.592203676700592},
  {'corpus_id': 855, 'score': 0.5917506217956543},
  {'corpus_id': 609, 'score': 0.591214120388031}],
 [{'corpus_id': 743, 'score': 0.7046071887016296},
  {'corpus_id': 856, 'score': 0.6982616186141968},
  {'corpus_id': 5, 'score': 0.6939384341239929},
  {'corpus_id': 14, 'score': 0.6787804961204529},
  {'corpus_id': 848, 'score': 0.6552160978317261},
  {'corpus_id': 858, 'score': 0.6430922746658325},
  {'corpus_id': 731, 'score': 0.6280298233032227},
  {'corpus_id': 51, 'score': 0.6268792152404785},
  {'corpus_id': 857, 'score': 0.6238223910331726},
  {'corpus_id': 595, 'score': 0.6204054355621338},
  {'corpus_id': 10, 'score': 0.613797664642334},
  {'corpus_id': 849, 'score': 0.6053906083106995},
  {'corpus_id': 603, 'score': 0.6043874621391296},
  {'corpus_id': 739, 'score': 0.5932090878486633},
  {'corpus_id': 2, 'score': 0.5916579961776733}],
 [{'corpus_id': 15, 'score': 0.8162885308265686},
  {'corpus_id': 22, 'score': 0.8021596670150757},
  {'corpus_id': 960, 'score': 0.6862269043922424},
  {'corpus_id': 23, 'score': 0.6836400032043457},
  {'corpus_id': 17, 'score': 0.6643123626708984},
  {'corpus_id': 958, 'score': 0.6632663011550903},
  {'corpus_id': 954, 'score': 0.657522976398468},
  {'corpus_id': 965, 'score': 0.6545995473861694},
  {'corpus_id': 962, 'score': 0.6470996737480164},
  {'corpus_id': 21, 'score': 0.643622875213623},
  {'corpus_id': 966, 'score': 0.6418255567550659},
  {'corpus_id': 957, 'score': 0.6353459358215332},
  {'corpus_id': 953, 'score': 0.6278712749481201},
  {'corpus_id': 963, 'score': 0.6188496351242065},
  {'corpus_id': 558, 'score': 0.6019988059997559}],
 [{'corpus_id': 21, 'score': 0.6731423139572144},
  {'corpus_id': 26, 'score': 0.656761646270752},
  {'corpus_id': 22, 'score': 0.6519067287445068},
  {'corpus_id': 16, 'score': 0.6175134181976318},
  {'corpus_id': 961, 'score': 0.614625096321106},
  {'corpus_id': 552, 'score': 0.6102508306503296},
  {'corpus_id': 488, 'score': 0.6010650396347046},
  {'corpus_id': 965, 'score': 0.5927466750144958},
  {'corpus_id': 557, 'score': 0.5908336639404297},
  {'corpus_id': 876, 'score': 0.5888129472732544},
  {'corpus_id': 956, 'score': 0.5884575843811035},
  {'corpus_id': 27, 'score': 0.5818235278129578},
  {'corpus_id': 960, 'score': 0.5807741284370422},
  {'corpus_id': 560, 'score': 0.5782907605171204},
  {'corpus_id': 964, 'score': 0.5758175253868103}],
 [{'corpus_id': 27, 'score': 0.6837142109870911},
  {'corpus_id': 20, 'score': 0.6660279631614685},
  {'corpus_id': 22, 'score': 0.6636203527450562},
  {'corpus_id': 23, 'score': 0.6627865433692932},
  {'corpus_id': 15, 'score': 0.6621841192245483},
  {'corpus_id': 18, 'score': 0.655827522277832},
  {'corpus_id': 25, 'score': 0.6496179103851318},
  {'corpus_id': 17, 'score': 0.6447826027870178},
  {'corpus_id': 562, 'score': 0.6272127032279968},
  {'corpus_id': 952, 'score': 0.6116434335708618},
  {'corpus_id': 26, 'score': 0.6046170592308044},
  {'corpus_id': 24, 'score': 0.6022622585296631},
  {'corpus_id': 21, 'score': 0.5981793999671936},
  {'corpus_id': 29, 'score': 0.5967258810997009},
  {'corpus_id': 558, 'score': 0.5957165360450745}],
 [{'corpus_id': 25, 'score': 0.7833572626113892},
  {'corpus_id': 20, 'score': 0.7339267134666443},
  {'corpus_id': 562, 'score': 0.7312639355659485},
  {'corpus_id': 24, 'score': 0.7076242566108704},
  {'corpus_id': 28, 'score': 0.6591058969497681},
  {'corpus_id': 558, 'score': 0.6418576836585999},
  {'corpus_id': 555, 'score': 0.6418389081954956},
  {'corpus_id': 19, 'score': 0.6418389081954956},
  {'corpus_id': 18, 'score': 0.6372805833816528},
  {'corpus_id': 29, 'score': 0.6207464933395386},
  {'corpus_id': 27, 'score': 0.6059139966964722},
  {'corpus_id': 873, 'score': 0.5796622037887573},
  {'corpus_id': 26, 'score': 0.5728760957717896},
  {'corpus_id': 963, 'score': 0.5657058954238892},
  {'corpus_id': 21, 'score': 0.5652600526809692}],
 [{'corpus_id': 20, 'score': 0.6988826990127563},
  {'corpus_id': 25, 'score': 0.6904535889625549},
  {'corpus_id': 963, 'score': 0.6850392818450928},
  {'corpus_id': 28, 'score': 0.6707807779312134},
  {'corpus_id': 562, 'score': 0.6602630615234375},
  {'corpus_id': 27, 'score': 0.6562045812606812},
  {'corpus_id': 18, 'score': 0.654888927936554},
  {'corpus_id': 29, 'score': 0.636951208114624},
  {'corpus_id': 19, 'score': 0.6232166886329651},
  {'corpus_id': 555, 'score': 0.6232166886329651},
  {'corpus_id': 21, 'score': 0.6158958077430725},
  {'corpus_id': 24, 'score': 0.6136872172355652},
  {'corpus_id': 22, 'score': 0.610843300819397},
  {'corpus_id': 26, 'score': 0.5741244554519653},
  {'corpus_id': 17, 'score': 0.5715242624282837}],
 [{'corpus_id': 20, 'score': 0.7375569939613342},
  {'corpus_id': 25, 'score': 0.6923964023590088},
  {'corpus_id': 18, 'score': 0.6589770317077637},
  {'corpus_id': 27, 'score': 0.6477075815200806},
  {'corpus_id': 29, 'score': 0.6390184760093689},
  {'corpus_id': 26, 'score': 0.6366058588027954},
  {'corpus_id': 21, 'score': 0.6297810077667236},
  {'corpus_id': 16, 'score': 0.6177908182144165},
  {'corpus_id': 23, 'score': 0.6158490180969238},
  {'corpus_id': 22, 'score': 0.6118105053901672},
  {'corpus_id': 17, 'score': 0.6028476357460022},
  {'corpus_id': 561, 'score': 0.5958266258239746},
  {'corpus_id': 557, 'score': 0.5857079029083252},
  {'corpus_id': 558, 'score': 0.5856971740722656},
  {'corpus_id': 28, 'score': 0.5848415493965149}],
 [{'corpus_id': 21, 'score': 0.7270982265472412},
  {'corpus_id': 26, 'score': 0.7216657400131226},
  {'corpus_id': 27, 'score': 0.6861923336982727},
  {'corpus_id': 560, 'score': 0.6584985256195068},
  {'corpus_id': 552, 'score': 0.6543893814086914},
  {'corpus_id': 557, 'score': 0.638780415058136},
  {'corpus_id': 488, 'score': 0.6354649066925049},
  {'corpus_id': 25, 'score': 0.6329774856567383},
  {'corpus_id': 20, 'score': 0.6280988454818726},
  {'corpus_id': 18, 'score': 0.6104192733764648},
  {'corpus_id': 961, 'score': 0.6029620170593262},
  {'corpus_id': 22, 'score': 0.6001685857772827},
  {'corpus_id': 28, 'score': 0.584618330001831},
  {'corpus_id': 550, 'score': 0.5827776193618774},
  {'corpus_id': 964, 'score': 0.5809420347213745}],
 [{'corpus_id': 22, 'score': 0.7985261082649231},
  {'corpus_id': 15, 'score': 0.6730513572692871},
  {'corpus_id': 17, 'score': 0.6673640608787537},
  {'corpus_id': 20, 'score': 0.6651847958564758},
  {'corpus_id': 25, 'score': 0.6505527496337891},
  {'corpus_id': 26, 'score': 0.6480331420898438},
  {'corpus_id': 555, 'score': 0.6064523458480835},
  {'corpus_id': 19, 'score': 0.6064523458480835},
  {'corpus_id': 562, 'score': 0.6042802929878235},
  {'corpus_id': 18, 'score': 0.6023831367492676},
  {'corpus_id': 29, 'score': 0.5993772149085999},
  {'corpus_id': 963, 'score': 0.5951353907585144},
  {'corpus_id': 21, 'score': 0.5929149389266968},
  {'corpus_id': 27, 'score': 0.5845437049865723},
  {'corpus_id': 16, 'score': 0.560309648513794}],
 [{'corpus_id': 23, 'score': 0.7280254364013672},
  {'corpus_id': 26, 'score': 0.6605275273323059},
  {'corpus_id': 21, 'score': 0.6287690997123718},
  {'corpus_id': 18, 'score': 0.607413113117218},
  {'corpus_id': 558, 'score': 0.6070884466171265},
  {'corpus_id': 20, 'score': 0.5900318622589111},
  {'corpus_id': 27, 'score': 0.589955747127533},
  {'corpus_id': 963, 'score': 0.5857213139533997},
  {'corpus_id': 478, 'score': 0.5792482495307922},
  {'corpus_id': 962, 'score': 0.5791430473327637},
  {'corpus_id': 957, 'score': 0.5753178596496582},
  {'corpus_id': 958, 'score': 0.5664184093475342},
  {'corpus_id': 960, 'score': 0.5623736381530762},
  {'corpus_id': 16, 'score': 0.5573943853378296},
  {'corpus_id': 28, 'score': 0.5548574924468994}],
 [{'corpus_id': 25, 'score': 0.6770980358123779},
  {'corpus_id': 24, 'score': 0.666445791721344},
  {'corpus_id': 562, 'score': 0.6535017490386963},
  {'corpus_id': 20, 'score': 0.6465952396392822},
  {'corpus_id': 29, 'score': 0.6344826221466064},
  {'corpus_id': 18, 'score': 0.6210514903068542},
  {'corpus_id': 28, 'score': 0.6020006537437439},
  {'corpus_id': 27, 'score': 0.5768365263938904},
  {'corpus_id': 23, 'score': 0.5643037557601929},
  {'corpus_id': 556, 'score': 0.5543553829193115},
  {'corpus_id': 555, 'score': 0.5538188815116882},
  {'corpus_id': 19, 'score': 0.5538188815116882},
  {'corpus_id': 558, 'score': 0.5398231744766235},
  {'corpus_id': 965, 'score': 0.5334302186965942},
  {'corpus_id': 15, 'score': 0.5316511988639832}],
 [{'corpus_id': 25, 'score': 0.7902926206588745},
  {'corpus_id': 20, 'score': 0.7756506204605103},
  {'corpus_id': 562, 'score': 0.712133526802063},
  {'corpus_id': 29, 'score': 0.6931737661361694},
  {'corpus_id': 24, 'score': 0.6090717911720276},
  {'corpus_id': 512, 'score': 0.604668378829956},
  {'corpus_id': 555, 'score': 0.5995250940322876},
  {'corpus_id': 19, 'score': 0.5995250940322876},
  {'corpus_id': 18, 'score': 0.5941852927207947},
  {'corpus_id': 26, 'score': 0.5862337350845337},
  {'corpus_id': 23, 'score': 0.5771629810333252},
  {'corpus_id': 28, 'score': 0.5751914978027344},
  {'corpus_id': 27, 'score': 0.5731672048568726},
  {'corpus_id': 510, 'score': 0.5484477281570435},
  {'corpus_id': 16, 'score': 0.5425311326980591}],
 [{'corpus_id': 26, 'score': 0.7040468454360962},
  {'corpus_id': 22, 'score': 0.701838493347168},
  {'corpus_id': 27, 'score': 0.6907350420951843},
  {'corpus_id': 20, 'score': 0.6663135290145874},
  {'corpus_id': 961, 'score': 0.643820583820343},
  {'corpus_id': 17, 'score': 0.6417897343635559},
  {'corpus_id': 18, 'score': 0.6385470032691956},

In [9]:
search_df

,path,jargon,layman
0,data/test_keywords/0a5325adb8861db65ff96c3516b...,Art installation,Art installation
1,data/test_keywords/0a5325adb8861db65ff96c3516b...,Composting area,Place where waste breaks down
2,data/test_keywords/0a5325adb8861db65ff96c3516b...,Pollination,Flowers being fertilized by insects
3,data/test_keywords/0a5325adb8861db65ff96c3516b...,Subject of sense experience,Person having a sensory experience
4,data/test_keywords/0a5325adb8861db65ff96c3516b...,Material processes,Natural processes in the environment
...,...,...,...
1007,data/test_keywords/06aef5ffb118088f7522be1b64e...,Finite number of flips,Polygon becomes convex in a limited number of ...
1008,data/test_keywords/06aef5ffb118088f7522be1b64e...,Self-crossing polygons,Polygons that intersect themselves
1009,data/test_keywords/06aef5ffb118088f7522be1b64e...,Θ(n²) time,Time grows with square of number of sides
1010,data/test_keywords/06aef5ffb118088f7522be1b64e...,O(n) time,Time grows linearly with number of sides
1011,data/test_keywords/06aef5ffb118088f7522be1b64e...,Generalized to higher dimensions,Works in 3D and beyond

In [10]:
results_df = pd.DataFrame(data={
    "query_index": range(len(search_results)),
    "result_id": [
        [result["corpus_id"] for result in single_results]
        for single_results in search_results
    ]
}).explode("result_id")
results_df.head()

   query_index result_id
0            0         0
0            0       861
0            0       597
0            0        11
0            0         1

In [11]:
results_df["layman"] = results_df["query_index"].apply(lambda i: search_df["layman"].iloc[i])
results_df["jargon"] = results_df["result_id"].apply(lambda i: search_df["jargon"].iloc[i])
results_df.head()

   query_index result_id            layman                       jargon
0            0         0  Art installation             Art installation
0            0       861  Art installation               Art exhibition
0            0       597  Art installation                 American art
0            0        11  Art installation  Participatory regime of art
0            0         1  Art installation              Composting area

In [12]:
search_results[0][0]

{'corpus_id': 0, 'score': 0.9999999403953552}